### ISSUE TITLE
Pull request sticky bar has white background

### ISSUE THREAD

**Issue by MarcinWieczorek** [CharlieEtienne/material-github#12]
Sticky bar has white background - can be seen on pull request details, for example here: https://github.com/django/django/pull/12572/files
Can be fixed with:
```css
.pr-toolbar.is-stuck {
    background-color: var(--bg3);
}
```

![scrot-1584803701](https://user-images.githubusercontent.com/3466984/77229633-4e842580-6b8f-11ea-9060-2926fc3fb520.png)
