### ISSUE TITLE
Account settings selected navigation white

### ISSUE THREAD

**Issue by legonigel** [CharlieEtienne/material-github#28]
See image below for https://github.com/settings/admin

![image](https://user-images.githubusercontent.com/2592586/82958620-9eee7980-9f6a-11ea-9e80-2e2c6ba0fb75.png)

Appears to be the first selector in the following css setting the background to white
```css
.menu-item.selected, .menu-item[aria-current]:not([aria-current=false]), .menu-item[aria-selected=true] {
    font-weight: 600;
    color: #24292e;
    cursor: default;
    background-color: #fff;
}
```
