### ISSUE TITLE
`t` file search has excessively bright highlight on the selected result

### ISSUE THREAD

**Issue by lf-** [CharlieEtienne/material-github#37]
![image](https://user-images.githubusercontent.com/6652840/86544313-c24a0400-beda-11ea-9768-a7304bfee69d.png)

This results in bad contrast on the text. To reproduce, go to the main page of a repository, press the `t` key, and type in part of a file name.

(also, a vertical line is just there because my GPU is dying, nothing to do with the styles 😅)

**Comment by legonigel** [comment]
This is fixed in the latest version. 

![image](https://user-images.githubusercontent.com/2592586/86627315-f5dd6a80-bf7c-11ea-8110-c227e5cbe03c.png)

You can update and it should work. (Go to Stylus > Manage and update style)

**Comment by lf-** [comment]
Are you sure? I just reinstalled it and this happened when I went to the Code tab of this repository, pressed the <kbd>t</kbd> key and typed in some letters:
![image](https://user-images.githubusercontent.com/6652840/86677010-0ce98000-bfb0-11ea-8aff-6fd15db23713.png)

**Comment by lf-** [comment]
To be clear this is not the site search where I think it was indeed fixed:
![image](https://user-images.githubusercontent.com/6652840/86677329-5a65ed00-bfb0-11ea-9f04-acb7c01dd5f8.png)

**Comment by legonigel** [comment]
@CharlieEtienne The offending css here is:
```css
.tree-browser-result[aria-selected=true] {
    background-color: #fff!important;
}
```

**Comment by CharlieEtienne** [comment]
Hi, thanks to both of you, you can update now.

**Comment by Gerrit0** [comment]
This also seems to be an issue in the notifications area.

```css
.notifications-list-item.navigation-focus {
  background-color: #f1f8ff!important;
}
```
