### ISSUE TITLE
Selected notification items are overly bright

### ISSUE THREAD

**Issue by Gerrit0** [CharlieEtienne/material-github#41]
Confirmed that this is still an issue with version 3.2.12.

```css
.notifications-list-item.navigation-focus {
  background-color: #f1f8ff!important;
}
```

Reproduction:
- Have at least one notification
- Go to https://github.com/notifications
- Press `j` to select the first item in the list

![image](https://user-images.githubusercontent.com/19329837/87226893-17ab6880-c354-11ea-9ee8-cf3ddf7acd10.png)

Looks like this fails to override since the background-color setting on line 1043 isn't marked with `!important`
