### ISSUE TITLE
The theme does not work in the activity tab

### ISSUE THREAD

**Issue by Suburbanno** [CharlieEtienne/material-github#8]
![image](https://user-images.githubusercontent.com/13632826/75610459-0faf0280-5af0-11ea-94b2-ee042a02c722.png)

**Comment by CharlieEtienne** [comment]
Hi, can you please update and check if it's solved ? I'm not sure but I think I commited without closing this issue...

Thanks

**Comment by Suburbanno** [comment]
@CharlieEtienne The issue has not been resolved.

**Comment by CharlieEtienne** [comment]
@Suburbanno Could you provide a link ? Are we speaking about github homepage (where you can see activity) ?
Thanks

**Comment by Suburbanno** [comment]
@CharlieEtienne 
![image](https://user-images.githubusercontent.com/13632826/77261568-1869a300-6c6e-11ea-9058-f7ca63d1d816.png)

**Comment by CharlieEtienne** [comment]
@Suburbanno ok that's weird, it works on mine... I'm trying to find out why.

**Comment by CharlieEtienne** [comment]
@Suburbanno mmh, I can't reproduce it... Are you able to identify the problematic selector ?

**Comment by Suburbanno** [comment]
@CharlieEtienne here?
:root {
    --github-green:  #28a745;
    --github-red:  #cb2431;
    --github-gray-background:  #fafbfc; <-
    --github-gray-text:  #6a737d;
    --github-faint-yellow:  #fffbdd;
}

**Comment by CharlieEtienne** [comment]
@Suburbanno could you try to update from https://userstyles.org/styles/174317/material-dark-github now ? I tried something...

**Comment by Suburbanno** [comment]
@CharlieEtienne I have the same problem, I cleared the browser cache and updated the style.

**Comment by CharlieEtienne** [comment]
maybe @Alex-D who liked your post could help to define which class is affected ?

**Comment by Alex-D** [comment]
It's due to usage of [Refined GitHub](https://github.com/sindresorhus/refined-github)
The selector/style injected by Refined GitHub is:

```css
.dashboard .js-all-activity-header + div {
    background-color: rgb(255, 255, 255);
    margin-top: 8px !important;
    border-width: 1px;
    border-style: solid;
    border-color: rgb(209, 213, 218);
    border-image: initial;
    border-radius: 3px;
}
```

So you need to override the background and border color :)

**Comment by CharlieEtienne** [comment]
Many thanks @Alex-D !

I updated theme on userstyles.org, hope it does a nice job (?)

```css
.dashboard .js-all-activity-header + div {
    background-color: var(--bg1);
    border-color:  var(--bg1);
}
```
